name: magento
type: "php:7.4"
disk: 2048
hooks:
  build: |
    composer install --no-dev --optimize-autoloader
    php bin/magento setup:static-content:deploy
web:
  locations:
    "/":
      root: "pub"
      passthru: "/index.php"
relationships:
  database:
    "type": "mysql:10.3"
    "disk": "256"

